annotations:
  category: Database
apiVersion: v1
appVersion: 3.4.10
description: etcd is a distributed key value store that provides a reliable way to
  store data across a cluster of machines
home: https://coreos.com/etcd/
icon: https://bitnami.com/assets/stacks/etcd/img/etcd-stack-110x117.png
keywords:
- etcd
- cluster
- database
- cache
- key-value
maintainers:
- email: containers@bitnami.com
  name: Bitnami
name: etcd
sources:
- https://github.com/bitnami/bitnami-docker-etcd
version: 4.9.1
