apiVersion: helm.operator-sdk/v1alpha1
kind: Etcd
metadata:
  name: example-etcd
spec:
  # Default values copied from <project_dir>/helm-charts/etcd/values.yaml
  
  affinity: {}
  allowNoneAuthentication: true
  auth:
    client:
      enableAuthentication: false
      secureTransport: false
      useAutoTLS: false
    peer:
      enableAuthentication: false
      secureTransport: false
      useAutoTLS: false
    rbac:
      enabled: true
  clusterDomain: cluster.local
  disasterRecovery:
    cronjob:
      historyLimit: 1
      podAnnotations: {}
      schedule: '*/30 * * * *'
      snapshotHistoryLimit: 1
    debug: true
    enabled: false
    pvc:
      size: 2Gi
      storageClassName: nfs
  etcd:
    initialClusterState: ""
  image:
    debug: false
    pullPolicy: IfNotPresent
    registry: docker.io
    repository: bitnami/etcd
    tag: 3.4.10-debian-10-r1
  livenessProbe:
    enabled: true
    failureThreshold: 5
    initialDelaySeconds: 60
    periodSeconds: 30
    successThreshold: 1
    timeoutSeconds: 5
  metrics:
    enabled: false
    podAnnotations:
      prometheus.io/port: "2379"
      prometheus.io/scrape: "true"
    serviceMonitor:
      enabled: false
  nodeSelector: {}
  pdb:
    enabled: false
  persistence:
    accessModes:
    - ReadWriteOnce
    annotations: {}
    enabled: true
    size: 8Gi
  podAnnotations: {}
  priorityClassName: ""
  readinessProbe:
    enabled: true
    failureThreshold: 5
    initialDelaySeconds: 60
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 5
  resources:
    limits: {}
    requests: {}
  securityContext:
    enabled: true
    fsGroup: 1001
    runAsUser: 1001
  service:
    annotations: {}
    nodePorts:
      clientPort: ""
      peerPort: ""
    peerPort: 2380
    port: 2379
    type: ClusterIP
  startFromSnapshot:
    enabled: false
  statefulset:
    podManagementPolicy: Parallel
    replicaCount: 1
    updateStrategy: RollingUpdate
  tolerations: []
  volumePermissions:
    enabled: false
    image:
      pullPolicy: Always
      registry: docker.io
      repository: bitnami/minideb
      tag: buster
    resources:
      limits: {}
      requests: {}
  
